### AuthController Login
POST https://localhost:5001/api/auth/login
Content-Type: application/json

{
    "name" : "zhao435021640@gmail.com",
    "password": "1",
    "role": "DEPARTMENT"
}

### AuthController Get Test
GET https://localhost:5001/api/auth
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InpoYW80MzUwMjE2NDBAZ21haWwuY29tIiwidW5pcXVlX25hbWUiOiJNYXJ0aW5pIiwicm9sZSI6IkNsZXJrIiwibmJmIjoxNTk2OTYzMzQyLCJleHAiOjE1OTcwNDk3NDIsImlhdCI6MTU5Njk2MzM0Mn0.bzRr_ma71tu1JLDIfs0Pkj5M_Urmq_KPaIsP1IqZZXh3P4sNSjrBZt0dSRciyXvqZwUKDgNPKlpnvlgrXUUdvw






### DeptController Get Collection Point
GET https://localhost:5001/api/dept
Authorization:  Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InpoYW80MzUwMjE2NDBAZ21haWwuY29tIiwidW5pcXVlX25hbWUiOiJNYXJ0aW5pIiwicm9sZSI6IkVNUExPWUVFIiwibmJmIjoxNTk3Mzg0ODQzLCJleHAiOjE1OTc0NzEyNDMsImlhdCI6MTU5NzM4NDg0M30.ATQEC7MNftEZNgEnC6dNTFJvJiDwxlFmIybXPKP_XvTmE-UJXftYiebdr0-3bnN2hOqjrXNkzLSCCBVGQRmMTg

### DeptController Update Collection Point
POST https://localhost:5001/api/dept
Content-Type: application/json

{
    "collectionPointId" : "Management School (11:00am)",
    "name": "Computer Science"
}





### DeptStaffController Get DeptStaff By Role
GET https://localhost:5001/api/deptStaff?deptName=Computer%20Science&roles=DEPTREP&roles=EMPLOYEE

### DeptStaffController Update Dept Rep
POST https://localhost:5001/api/deptStaff
Content-Type: application/json

{
    "email" : "zhao435021640@gmail.com"
}





### RequisitionController Create Requisition
POST https://localhost:5001/api/requisition
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InpoYW80MzUwMjE2NDBAZ21haWwuY29tIiwidW5pcXVlX25hbWUiOiJNYXJ0aW5pIiwicm9sZSI6IkVNUExPWUVFIiwibmJmIjoxNTk3NDc0NTE1LCJleHAiOjE1OTc1NjA5MTUsImlhdCI6MTU5NzQ3NDUxNX0.fdBcISHitmw6KXrYuY4VRghp0CPekwOXDc9Kf9n8GiusGwjdPyXVJq3Wo8liFp8rjGPa1u9q4ae7kxAapE18Pg
Content-Type: application/json

[{
    "itemId" :"89C36910-05F3-4C02-A797-01C8EB7460AB",
    "need":1
},
{
    "itemId" :"17847B64-20C3-4A23-BFEF-02B3E5FD36FF",
    "need":2
}]

### RequisitionController Get Requisition By Role
GET https://localhost:5001/api/requisition
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InpoYW80MzUwMjE2NDBAZ21haWwuY29tIiwidW5pcXVlX25hbWUiOiJNYXJ0aW5pIiwicm9sZSI6IkVNUExPWUVFIiwibmJmIjoxNTk3NDc0NTE1LCJleHAiOjE1OTc1NjA5MTUsImlhdCI6MTU5NzQ3NDUxNX0.fdBcISHitmw6KXrYuY4VRghp0CPekwOXDc9Kf9n8GiusGwjdPyXVJq3Wo8liFp8rjGPa1u9q4ae7kxAapE18Pg

### RequisitionController Get Requisition By Status
GET https://localhost:5001/api/requisition/APPLIED