### AuthController Login Employee
POST https://localhost:5001/api/auth/login
Content-Type: application/json

{
    "name" : "zhao435021640@gmail.com",
    "password": "1",
    "role": "DEPARTMENT"
}

### AuthController Login DeptHead
POST https://localhost:5001/api/auth/login
Content-Type: application/json

{
    "name" : "Meka",
    "password": "1",
    "role": "DEPARTMENT"
}

### AuthController Login Clerk
POST https://localhost:5001/api/auth/login
Content-Type: application/json

{
    "name" : "win",
    "password": "1",
    "role": "STORE"
}

### AuthController Get Test
GET https://localhost:5001/api/auth
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InpoYW80MzUwMjE2NDBAZ21haWwuY29tIiwidW5pcXVlX25hbWUiOiJNYXJ0aW5pIiwicm9sZSI6IkNsZXJrIiwibmJmIjoxNTk2OTYzMzQyLCJleHAiOjE1OTcwNDk3NDIsImlhdCI6MTU5Njk2MzM0Mn0.bzRr_ma71tu1JLDIfs0Pkj5M_Urmq_KPaIsP1IqZZXh3P4sNSjrBZt0dSRciyXvqZwUKDgNPKlpnvlgrXUUdvw






### DeptController Get Collection Point
GET https://localhost:5001/api/dept
Authorization:  Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InpoYW80MzUwMjE2NDBAZ21haWwuY29tIiwidW5pcXVlX25hbWUiOiJNYXJ0aW5pIiwicm9sZSI6IkVNUExPWUVFIiwibmJmIjoxNTk3Mzg0ODQzLCJleHAiOjE1OTc0NzEyNDMsImlhdCI6MTU5NzM4NDg0M30.ATQEC7MNftEZNgEnC6dNTFJvJiDwxlFmIybXPKP_XvTmE-UJXftYiebdr0-3bnN2hOqjrXNkzLSCCBVGQRmMTg

### DeptController Update Collection Point
POST https://localhost:5001/api/dept
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1la2FAZ21haWwuY29tIiwidW5pcXVlX25hbWUiOiJNZWthIiwicm9sZSI6IkRFUFRIRUFEIiwibmJmIjoxNTk3NTYzMDI4LCJleHAiOjE1OTc2NDk0MjgsImlhdCI6MTU5NzU2MzAyOH0.GPwfv3mNo8CmMmf_-zX0npOA4g1zX6YeuTkFK7D3iSC0W_OYsgeobVvRN1GhVxLzxMvk-AxEGWCS5EEw9nINAw
Content-Type: application/json

"University Hospital (11:00 AM)"





### DeptStaffController Get DeptStaff By Role
GET https://localhost:5001/api/deptStaff?deptName=Computer%20Science&roles=DEPTREP&roles=EMPLOYEE

### DeptStaffController Update Dept Rep
POST https://localhost:5001/api/deptStaff
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1la2FAZ21haWwuY29tIiwidW5pcXVlX25hbWUiOiJNZWthIiwicm9sZSI6IkRFUFRIRUFEIiwibmJmIjoxNTk3NTYzMDI4LCJleHAiOjE1OTc2NDk0MjgsImlhdCI6MTU5NzU2MzAyOH0.GPwfv3mNo8CmMmf_-zX0npOA4g1zX6YeuTkFK7D3iSC0W_OYsgeobVvRN1GhVxLzxMvk-AxEGWCS5EEw9nINAw
Content-Type: application/json

"zhao435021640@gmail.com"





### RequisitionController Create Requisition
POST https://localhost:5001/api/requisition
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InpoYW80MzUwMjE2NDBAZ21haWwuY29tIiwidW5pcXVlX25hbWUiOiJNYXJ0aW5pIiwicm9sZSI6IkVNUExPWUVFIiwibmJmIjoxNTk3NTY3NTM3LCJleHAiOjE1OTc2NTM5MzcsImlhdCI6MTU5NzU2NzUzN30.VsO1F8cuUHDMI3q6eK14t3kqQsqIzxhBcCurty-JjGHW7GfnGoUtcz_YvLxAwl1FNhFyPf6dEgfALLILzidVnw
Content-Type: application/json

[{
    "itemId" :"37FDA11A-2E77-4208-AE72-02C7D1EEC084",
    "need":1
},
{
    "itemId" :"B9203A2B-ACEB-44E3-AAEB-065A56E94A9B",
    "need":2
}]

### RequisitionController Get Requisition By DeptStaff
GET https://localhost:5001/api/requisition
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InpoYW80MzUwMjE2NDBAZ21haWwuY29tIiwidW5pcXVlX25hbWUiOiJNYXJ0aW5pIiwicm9sZSI6IkVNUExPWUVFIiwibmJmIjoxNTk3NTU4NjE0LCJleHAiOjE1OTc2NDUwMTQsImlhdCI6MTU5NzU1ODYxNH0.4tog-4rYlPDHEruIxEoG_qLGf-_RPNxbzvvW1JyVsxTHDGzqlcgLP-qr-pfYANA-_fb3PLRahW1nJR8z-oFMRA

### RequisitionController Get Requisition By Status
GET https://localhost:5001/api/requisition/APPLIED
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IndpbkBnbWFpbC5jb20iLCJ1bmlxdWVfbmFtZSI6IldpbiIsInJvbGUiOiJDTEVSSyIsIm5iZiI6MTU5NzQ4MjI1NCwiZXhwIjoxNTk3NTY4NjU0LCJpYXQiOjE1OTc0ODIyNTR9.oLfiCfdt5GUAnwqJY3Ez9PSw1vI7716urjlA1jUFkFkHUEnrOwEpeuDgSwYu50CpiUlW6RtOqNMUD4hKOPU6-w



### RetrievalController Create Retrieval
POST https://localhost:5001/api/retrieval
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IndpbkBnbWFpbC5jb20iLCJ1bmlxdWVfbmFtZSI6IldpbiIsInJvbGUiOiJDTEVSSyIsIm5iZiI6MTU5NzU3MDc2OCwiZXhwIjoxNTk3NjU3MTY4LCJpYXQiOjE1OTc1NzA3Njh9.KvczbR8-NYGH07ObQDXikZ9EE-nVwIYtGPOHg37M50zeRGcsFXRwIQcq4mjZEXWYBwHilbNRQy-hm8-4agSerg
Content-Type: application/json

["F7695283-EAF6-467E-AFE9-65BAA56B5207", "200B4F6B-EB11-4217-B858-FD8C2837C176"]