### AuthController Login Employee
POST https://localhost:5001/api/auth
Content-Type: application/json

{
    "name" : "zhao435021640@gmail.com",
    "password": "1",
    "role": "DEPARTMENT"
}

### AuthController Login DeptHead
POST https://localhost:5001/api/auth
Content-Type: application/json

{
    "name" : "Meka",
    "password": "1",
    "role": "DEPARTMENT"
}

### AuthController Login Clerk
POST https://localhost:5001/api/auth
Content-Type: application/json

{
    "name" : "win",
    "password": "1",
    "role": "STORE"
}

### AuthController Get Test
GET https://localhost:5001/api/auth
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InpoYW80MzUwMjE2NDBAZ21haWwuY29tIiwidW5pcXVlX25hbWUiOiJNYXJ0aW5pIiwicm9sZSI6IkNsZXJrIiwibmJmIjoxNTk2OTYzMzQyLCJleHAiOjE1OTcwNDk3NDIsImlhdCI6MTU5Njk2MzM0Mn0.bzRr_ma71tu1JLDIfs0Pkj5M_Urmq_KPaIsP1IqZZXh3P4sNSjrBZt0dSRciyXvqZwUKDgNPKlpnvlgrXUUdvw






### DeptController Get Collection Point
GET https://localhost:5001/api/dept
Authorization:  Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InpoYW80MzUwMjE2NDBAZ21haWwuY29tIiwidW5pcXVlX25hbWUiOiJNYXJ0aW5pIiwicm9sZSI6IkVNUExPWUVFIiwibmJmIjoxNTk3Mzg0ODQzLCJleHAiOjE1OTc0NzEyNDMsImlhdCI6MTU5NzM4NDg0M30.ATQEC7MNftEZNgEnC6dNTFJvJiDwxlFmIybXPKP_XvTmE-UJXftYiebdr0-3bnN2hOqjrXNkzLSCCBVGQRmMTg

### DeptController Update Collection Point
POST https://localhost:5001/api/dept
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1la2FAZ21haWwuY29tIiwidW5pcXVlX25hbWUiOiJNZWthIiwicm9sZSI6IkRFUFRIRUFEIiwibmJmIjoxNTk3NTYzMDI4LCJleHAiOjE1OTc2NDk0MjgsImlhdCI6MTU5NzU2MzAyOH0.GPwfv3mNo8CmMmf_-zX0npOA4g1zX6YeuTkFK7D3iSC0W_OYsgeobVvRN1GhVxLzxMvk-AxEGWCS5EEw9nINAw
Content-Type: application/json

"University Hospital (11:00 AM)"





### DeptStaffController Get DeptStaff By Role
GET https://localhost:5001/api/deptStaff?roles=DEPTREP&roles=EMPLOYEE
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1la2FAZ21haWwuY29tIiwidW5pcXVlX25hbWUiOiJNZWthIiwicm9sZSI6IkRFUFRIRUFEIiwibmJmIjoxNTk3NjM0Mzg5LCJleHAiOjE1OTc3MjA3ODksImlhdCI6MTU5NzYzNDM4OX0.Klg64dYAY0kpMd02sSbdOfQuooWq11C4Y0BnXSdqY4UclgOXkw8xikwq9PEMb6uIeKWLxHj7YxI6YNdxqZSlYQ

### DeptStaffController Update Dept Rep
POST https://localhost:5001/api/deptStaff
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1la2FAZ21haWwuY29tIiwidW5pcXVlX25hbWUiOiJNZWthIiwicm9sZSI6IkRFUFRIRUFEIiwibmJmIjoxNTk3NTYzMDI4LCJleHAiOjE1OTc2NDk0MjgsImlhdCI6MTU5NzU2MzAyOH0.GPwfv3mNo8CmMmf_-zX0npOA4g1zX6YeuTkFK7D3iSC0W_OYsgeobVvRN1GhVxLzxMvk-AxEGWCS5EEw9nINAw
Content-Type: application/json

"zhao435021640@gmail.com"





### RequisitionController Create Requisition
POST https://localhost:5001/api/requisition
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InpoYW80MzUwMjE2NDBAZ21haWwuY29tIiwidW5pcXVlX25hbWUiOiJNYXJ0aW5pIiwicm9sZSI6IkVNUExPWUVFIiwibmJmIjoxNTk3NTY3NTM3LCJleHAiOjE1OTc2NTM5MzcsImlhdCI6MTU5NzU2NzUzN30.VsO1F8cuUHDMI3q6eK14t3kqQsqIzxhBcCurty-JjGHW7GfnGoUtcz_YvLxAwl1FNhFyPf6dEgfALLILzidVnw
Content-Type: application/json

[{
    "itemId" :"2B8ADAE6-916B-4C65-97A4-032702BB75B0",
    "need":1
},
{
    "itemId" :"AA034FDB-021D-4F4C-BE03-03A644F2A66C",
    "need":2
}]

### RequisitionController Get Requisition By DeptStaff
GET https://localhost:5001/api/requisition
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InpoYW80MzUwMjE2NDBAZ21haWwuY29tIiwidW5pcXVlX25hbWUiOiJNYXJ0aW5pIiwicm9sZSI6IkVNUExPWUVFIiwibmJmIjoxNTk3NTU4NjE0LCJleHAiOjE1OTc2NDUwMTQsImlhdCI6MTU5NzU1ODYxNH0.4tog-4rYlPDHEruIxEoG_qLGf-_RPNxbzvvW1JyVsxTHDGzqlcgLP-qr-pfYANA-_fb3PLRahW1nJR8z-oFMRA

### RequisitionController Get Requisition By Status
GET https://localhost:5001/api/requisition/APPROVED
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IndpbkBnbWFpbC5jb20iLCJ1bmlxdWVfbmFtZSI6IldpbiIsInJvbGUiOiJDTEVSSyIsIm5iZiI6MTU5NzY3NzcyNCwiZXhwIjoxNTk3NzY0MTI0LCJpYXQiOjE1OTc2Nzc3MjR9.5kj5iNNI1qE0RSIC-pPHaBHDIIhEcxzeal0Jc_6MP3tMXDN-FiU4loMQT_j5plptPXJUr5QXXrQ2KkgKrJDGgw

### RequisitionController Review Requisition
PUT https://localhost:5001/api/requisition/2edba6ce-95a0-4137-8622-c075fa9b24e7
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1la2FAZ21haWwuY29tIiwidW5pcXVlX25hbWUiOiJNZWthIiwicm9sZSI6IkRFUFRIRUFEIiwibmJmIjoxNTk3ODQzMzEyLCJleHAiOjE1OTc5Mjk3MTIsImlhdCI6MTU5Nzg0MzMxMn0.F1t2xuv8UTLcvcbG_GtZbalxLbcPKWpgeuO3DB8cOFRUfRsX_0-3yGd51ZJ7Fx3aBnkKFnfpKvVsrEqiZwi9Sg
Content-Type: application/json

"APPROVED"





### RetrievalController Create Retrieval
POST https://localhost:5001/api/retrieval
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IndpbkBnbWFpbC5jb20iLCJ1bmlxdWVfbmFtZSI6IldpbiIsInJvbGUiOiJDTEVSSyIsIm5iZiI6MTU5NzY3MTIyOCwiZXhwIjoxNTk3NzU3NjI4LCJpYXQiOjE1OTc2NzEyMjh9.LXn0_V1huHTOFKGrVA0HN-BADKVojx8Q9mX03lV9hbx0kYubQpJiGhL-nd-TQ1-RiTZ-oX7g8Bm8Vhic_vRFBw
Content-Type: application/json

["E9FF7B45-4FCA-438A-ADC4-20516EB15177"]


### RetrievalController Update Retrieval Actual Quantity
POST https://localhost:5001/api/retrieval/D572E24A-03E3-46C3-9C4A-C3CC88E3C89F
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IndpbkBnbWFpbC5jb20iLCJ1bmlxdWVfbmFtZSI6IldpbiIsInJvbGUiOiJDTEVSSyIsIm5iZiI6MTU5NzU3MDc2OCwiZXhwIjoxNTk3NjU3MTY4LCJpYXQiOjE1OTc1NzA3Njh9.KvczbR8-NYGH07ObQDXikZ9EE-nVwIYtGPOHg37M50zeRGcsFXRwIQcq4mjZEXWYBwHilbNRQy-hm8-4agSerg
Content-Type: application/json

[{
    "itemId" :"A375AAC9-CD3B-40F1-9E5C-8555A1F4ED00",
    "totalQtyRetrieved" : 2
},
{
    "itemId" :"54ADF800-F952-4843-BCFF-D8655E8F8924",
    "totalQtyRetrieved" : 2
}]

### OrderController Create order
POST https://localhost:5001/api/order
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IndpbkBnbWFpbC5jb20iLCJ1bmlxdWVfbmFtZSI6IldpbiIsInJvbGUiOiJDTEVSSyIsIm5iZiI6MTU5ODA5Nzk4MSwiZXhwIjoxNTk4MTg0MzgxLCJpYXQiOjE1OTgwOTc5ODF9.qdbcKKLdh6qy808HyyCgSm8zw1A-tt5E6f2W7lVbX3lydV5HVC03nrD59AiYnKM8FjUZFv84arVCNhsTTFtEQw
Content-Type: application/json

[{
    "supplierId": "235156e0-24bc-4e02-812a-094415fa55ec",
    "orderItems": [{
        "itemId": "ea502710-6f92-4611-a335-023c54cbf6bc",
        "orderedQty": 10,
    }],
},
{
    "supplierId": "34ae1357-fbe4-48fd-86d0-77d8e53c3482",
    "orderItems": [{
        "itemId": "ea502710-6f92-4611-a335-023c54cbf6bc",
        "orderedQty": 5,
    }],
},
{
    "supplierId": "3ca7ddce-6c3f-49e1-a200-f50ea438f3e6",
    "orderItems": [{
        "itemId": "ea502710-6f92-4611-a335-023c54cbf6bc",
        "orderedQty": 5,
    }],
}]